---
title: "National Firearm Permit Statistics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown


```{r cars}


library(tidyverse)
library(zoo)
library(usmap)

options(stringsAsFactors = FALSE)

# retrieve data from comma delimited file/adjust data types
permits <- read.csv("nics-firearm-background-checks.csv")
permits$month <- as.yearmon(permits$month)

```

## Plots


Total Permits by State 2017

```{r pressure, echo=FALSE}
permits2017 <- filter(permits, 
                       permits$month >= as.yearmon("2017-01") &
                       permits$month < as.yearmon("2018-01"))

usmap::plot_usmap(data = permits2017, values = "totals", lines = "red") + 
  scale_fill_continuous(
    low = "white", high = "red", name = "Permits By State 2017", label = scales::comma
  ) + theme(legend.position = "right")
```

Texas long gun vs handgun permits 2000-2017

```{r}
# Texas long gun vs hand gun permits over time
texas_perm <- filter(permits, 
                      permits$state == "Texas")

ggplot(data = texas_perm) + 
  geom_line(mapping = aes(x = month, y = long_gun, color="Long Gun")) +
  geom_line(mapping = aes(x = month, y = handgun, color="Handgun"))
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
